import datetime
dt1 = datetime.datetime.now()
print(dt1)
print(dt1.strftime("%A"))
print(dt1.strftime("%a"))
print(dt1.strftime("%W"))
print(dt1.strftime("%d"))
print(dt1.strftime("%y"))
print(dt1.strftime("%Y"))
print(dt1.strftime("%H"))
print(dt1.strftime("%S"))
print(dt1.strftime("%M"))
# print(dt1.strftime("%P"))
# print(dt1.strftime("%P"))

